version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/install:
          build: 'npm install -D'
      - cypress/run:
          requires:
            - cypress/install
          record: true # record results on Cypress Dashboards