version: 2.1
parameters: 
    git-branch: 
      default: "non-existing-branch"
      type: string
orbs:
  cypress: cypress-io/cypress@1
executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.17.0-chrome91-ff89'
workflows:
  build:
    jobs:
      - cypress/install:
          working_directory: test/e2e
          cache-key: 'cache-{{ checksum "test/e2e/package.json" }}'
          filters:
              branches:
                only:
                    - << pipeline.parameters.git-branch >>
          # cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "test/e2e/package.json" }}'
      - cypress/run:
          requires:
            - cypress/install
          executor: with-chrome
          browser: chrome
          working_directory: test/e2e
          attach-workspace: true
          no-workspace: true
          # parallel: true
          parallelism: 4
          # group: run 1
          command: npm run cy-reg-parallel-bork
          filters:
              branches:
                only:
                    - << pipeline.parameters.git-branch >>
          # command: npm run cy-smoke-2-email-parallels
          # command: echo CIRCLE_NODE_INDEX
      # - cypress/run:
      #     requires:
      #       - cypress/install
      #     executor: with-chrome
      #     browser: chrome
      #     working_directory: test/e2e
      #     attach-workspace: true
      #     # cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "test/e2e/package.json" }}'
      #     # parallel: true
      #     parallelism: 1
      #     # group: run 1
      #     command: npm run cy3
      # - cypress/run:
      #     requires:
      #       - cypress/install
      #     executor: with-chrome
      #     browser: chrome
      #     working_directory: test/e2e
      #     cache-key: 'cache-{{ arch }}-{{ .Branch }}-{{ checksum "test/e2e/package.json" }}'
      #     parallel: true
      #     parallelism: 3
      #     group: run 2
      #     command: npm run cy2
      #dsadsads


